name: Bug Report
description: File a bug report.
title: "🐛 "
labels: ["bug"]
projects: ["GCTC-NTGC/8"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!      
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Add any additional details that could assist with troubleshooting/fixing the issue.
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: Paste a screenshot to help illustrate the problem.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we make this happen again when testing?

